language: node_js
node_js:
- '0.10'
- '4'
sudo: false
install: npm install
services:
- docker
addons:
  sonarqube: true
script:
- npm run ci
- 'if [ -v SONAR_TOKEN ]; then docker pull pierrevincent/sonar-runner && docker run --rm -v $(pwd):/data pierrevincent/sonar-runner -Dsonar.host.url=https://sonarqube.com
  -Dsonar.login=$SONAR_TOKEN -Dsonar.github.oauth=$SONAR_GITHUB; fi'
